### PR TITLE
Added support for no SSL Certificate check

### PR DESCRIPTION
**Pull request by iam1980**

### CODE REVIEW

**Comment by miglen** [comment]
Hey @jseidl can you please review and merge this is a great feature.

**Comment by jseidl** [comment]
There's a typo in the getopts (sslcheck, should be nosslcheck as further
down in the code)

I'll try to accept the push then do the fix later this week

**Comment by miglen** [comment]
Hey @iam1980 please check it out :)

**Comment by iam1980** [comment]
done. should be good to go now.

**Pull request merged**
