### PR TITLE
Refactor to python3

### PR DESCRIPTION
**Pull request by samueloph**
Based on 2to3, also did some changes related to flake8 and trailing whitespaces.

Tested both python scripts and they worked, though the test was simple, so I may have missed something.

I didn't want to switch to fstrings because it would required more work.

I appreciate if you could have some time to test it and ack the changes :)

Thanks

### CODE REVIEW

**Comment by jseidl** [comment]
Thanks for you work. I'll test it through the weekend and get your PR going!

**Comment by rhertzog** [comment]
@jseidl Any update? It would be great to release a version that works on Python 3.

**Comment by jseidl** [comment]
Really didn't had time to test out this PR due holidays. Gonna just trust and merge, if anything breaks we can fix it :)

**Comment by samueloph** [comment]
I realized 2to3 added some unneeded `list(.keys())` changes, these should not be needed but I don' t think they break functionality.

**Pull request merged**
